apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: jardel-app
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mysql
          image: 'mysql:5.6'
          ports:
            - containerPort: 3306
              name: mysql