apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: jardel-app
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 3
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: 'bitnami/wordpress:6.2.0'
          ports:
            - containerPort: 8080